# Generated by Django 3.2.4 on 2021-06-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Age',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
