# Generated by Django 3.2.4 on 2021-06-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='QNo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
    ]
